# Generated by Django 3.2.5 on 2021-08-07 12:37

from django.db import migrations
from currency.models import Rate


def forwards(apps, schema_editor):
    for rate in Rate.objets.all():
        rate.type_new = 1 if 'eur' in rate.type else 0
        rate.save()


def backwards(apps, schema_editor):
    print('HEELO FROM BACKWARDS!')


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0002_rate_type_new'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
