# Generated by Django 3.2.4 on 2021-06-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email_from',
        ),
    ]
