# Generated by Django 3.2.5 on 2021-08-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_bank_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.bank'),
        ),
    ]
