# Generated by Django 3.2.5 on 2021-08-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210807_1237'),
    ]

    operations = [
    ]
