# Generated by Django 3.2.5 on 2021-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='code_name',
            field=models.CharField(default='privatbank', max_length=64, unique=True),
        ),
    ]
