# Generated by Django 3.2.5 on 2021-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210704_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Bank',
        ),
    ]
