# Generated by Django 3.2.5 on 2021-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_bank_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
