# Generated by Django 3.2.5 on 2021-08-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_remove_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.bank'),
        ),
    ]
