# Generated by Django 3.2.5 on 2021-09-08 15:57

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.logo_directory_path),
        ),
    ]
